name: Build and push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          APP_NAME=http-tester
          IMAGE_BASE=ghcr.io/jamesmcdonald/$APP_NAME
          VERSION=$(git describe --tags --always --dirty)
          IMAGE_NAME=$IMAGE_BASE:$VERSION
          LATEST=$IMAGE_BASE:latest
          
          docker build -t $IMAGE_NAME .
          docker tag $IMAGE_NAME $LATEST
      
      - name: Push
        run: |
          docker push $IMAGE_NAME
          docker push $LATEST

